version: "3.8"
services:
  mysql:
    container_name: mall_mysql
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/logs
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: redis:5.0.14
    container_name: mall_redis
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    privileged: true
    ports:
    - "6379:6379"
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data  --console-address ":9000" --address ":9090"
    ports:
    - "9000:9000"
    - "9090:9090"
    restart: always

  postgres:
    image: postgres:15
    container_name: compose-postgresql
    hostname: postgresql
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./dbdata/pgdata/data:/var/lib/postgresql/data
      - ./conf/sql:/docker-entrypoint-initdb.d/      

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.95.1
    container_name: compose-victoria-metrics
    hostname: victoria-metrics
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://victoria-metrics:8428/-/healthy"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8428"
    volumes:
      - ./dbdata/tsdbdata:/victoria-metrics-data

  hertzbeat:
    image: apache/hertzbeat
    container_name: compose-hertzbeat
    hostname: hertzbeat
    restart: always
    environment:
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
    depends_on:
      postgres:
        condition: service_healthy
      victoria-metrics:
        condition: service_healthy
    volumes:
      - ./conf/application.yml:/opt/hertzbeat/config/application.yml
      - ./conf/sureness.yml:/opt/hertzbeat/config/sureness.yml
      - ./logs:/opt/hertzbeat/logs
      - ./ext-lib:/opt/hertzbeat/ext-lib
    ports:
      - "1157:1157"
      - "1158:1158"
  
